import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['en', 'ms', 'zh_Hans', 'ta', 'id', 'ru', 'de', 'tl'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? msText = '',
    String? zh_HansText = '',
    String? taText = '',
    String? idText = '',
    String? ruText = '',
    String? deText = '',
    String? tlText = '',
  }) =>
      [
        enText,
        msText,
        zh_HansText,
        taText,
        idText,
        ruText,
        deText,
        tlText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // SignIn
  {
    'c2g7dlbt': {
      'en': 'Welcome to',
      'de': 'Willkommen zu',
      'id': 'Selamat Datang di',
      'ms': 'Selamat datang ke',
      'ru': 'Добро пожаловать в',
      'ta': 'வரவேற்கிறோம்',
      'tl': 'Maligayang pagdating sa',
      'zh_Hans': '欢迎来到',
    },
    'c3xxr3hm': {
      'en': 'Asia\'s Fashion Expert',
      'de': 'Asiens Modeexperte',
      'id': 'Pakar Mode Asia',
      'ms': 'Pakar Fesyen Asia',
      'ru': 'Эксперт азиатской моды',
      'ta': 'ஆசியாவின் ஃபேஷன் நிபுணர்',
      'tl': 'Dalubhasa sa Fashion ng Asia',
      'zh_Hans': '亚洲时尚专家',
    },
    'zk1iypno': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'noyg2x87': {
      'en': 'Enter your phone number',
      'de': 'Gib deine Telefonnummer ein',
      'id': 'Masukkan nomor telepon Anda',
      'ms': 'Masukkan nombor telefon anda',
      'ru': 'Введите свой номер телефона',
      'ta': 'உங்கள் தொடர்பு எண்ணை அளிக்கவும்',
      'tl': 'Ilagay ang iyong numero ng telepono',
      'zh_Hans': '输入你的电话号码',
    },
    '5tsiakp9': {
      'en': 'Phone number is required.',
      'de': 'Telefonnummer ist erforderlich.',
      'id': 'Nomor telepon diperlukan.',
      'ms': 'Nombor telefon diperlukan.',
      'ru': 'Требуется номер телефона.',
      'ta': 'தொலைபேசி எண் தேவை.',
      'tl': 'Kinakailangan ang numero ng telepono.',
      'zh_Hans': '需要电话号码。',
    },
    '75ci82a7': {
      'en': 'Please choose an option from the dropdown',
      'de': 'Bitte wählen Sie eine Option aus der Dropdown-Liste aus',
      'id': 'Silakan pilih opsi dari menu tarik-turun',
      'ms': 'Sila pilih pilihan daripada menu lungsur',
      'ru': 'Пожалуйста, выберите вариант из раскрывающегося списка',
      'ta': 'கீழ்தோன்றலில் இருந்து ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும்',
      'tl': 'Mangyaring pumili ng opsyon mula sa dropdown',
      'zh_Hans': '请从下拉列表中选择一个选项',
    },
    'gnjewztq': {
      'en': 'Send Code',
      'de': 'Code senden',
      'id': 'Kirim Kode',
      'ms': 'Hantar Kod',
      'ru': 'Отправить код',
      'ta': 'குறியீட்டை அனுப்பவும்',
      'tl': 'Magpadala ng code',
      'zh_Hans': '发送代码',
    },
    'b7er5pp3': {
      'en': 'Sign in',
      'de': 'Melden Sie sich ohne etwas an',
      'id': 'Masuk tanpa apa pun',
      'ms': 'Log masuk tanpa apa-apa',
      'ru': 'Войти без ничего',
      'ta': 'எதுவும் இல்லாமல் உள்நுழைக',
      'tl': 'Mag-sign in nang walang anuman',
      'zh_Hans': '无需任何操作即可登录',
    },
    '642uk7yd': {
      'en': 'Home',
      'de': 'Heim',
      'id': 'Rumah',
      'ms': 'Rumah',
      'ru': 'Дом',
      'ta': 'வீடு',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // ResultsPage
  {
    'yofyke0n': {
      'en': 'Welcome,',
      'de': 'Willkommen,',
      'id': 'Selamat datang,',
      'ms': 'selamat datang,',
      'ru': 'Добро пожаловать,',
      'ta': 'வரவேற்பு,',
      'tl': 'maligayang pagdating,',
      'zh_Hans': '欢迎，',
    },
    'r772mbx7': {
      'en': 'You Completed All Activities!',
      'de': 'Sie haben alle Aktivitäten abgeschlossen!',
      'id': 'Anda Menyelesaikan Semua Aktivitas!',
      'ms': 'Anda Selesai Semua Aktiviti!',
      'ru': 'Вы завершили все действия!',
      'ta': 'நீங்கள் அனைத்து செயல்பாடுகளையும் முடித்துவிட்டீர்கள்!',
      'tl': 'Nakumpleto Mo ang Lahat ng Aktibidad!',
      'zh_Hans': '您完成了所有活动！',
    },
    '5z2msrpf': {
      'en': 'Explore activity results below.',
      'de': 'Entdecken Sie unten die Aktivitätsergebnisse.',
      'id': 'Jelajahi hasil aktivitas di bawah ini.',
      'ms': 'Teroka hasil aktiviti di bawah.',
      'ru': 'Изучите результаты деятельности ниже.',
      'ta': 'செயல்பாட்டு முடிவுகளை கீழே ஆராயவும்.',
      'tl': 'Galugarin ang mga resulta ng aktibidad sa ibaba.',
      'zh_Hans': '浏览下面的活动结果。',
    },
    'nyrn32xb': {
      'en': 'Alt Home ',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ouhjvogq': {
      'en': 'Home',
      'de': 'Heim',
      'id': 'Rumah',
      'ms': 'Rumah',
      'ru': 'Дом',
      'ta': 'வீடு',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // CheckInConfirmed
  {
    'uo5wt6fm': {
      'en': 'You\'ve checked in!',
      'de': 'Sie haben eingecheckt!',
      'id': 'Anda telah check-in!',
      'ms': 'Anda telah mendaftar masuk!',
      'ru': 'Вы зарегистрировались!',
      'ta': 'நீங்கள் செக்-இன் செய்துவிட்டீர்கள்!',
      'tl': 'Naka-check in ka na!',
      'zh_Hans': '您已签到！',
    },
    '373ui5bm': {
      'en': 'Continue',
      'de': 'Weitermachen',
      'id': 'Melanjutkan',
      'ms': 'teruskan',
      'ru': 'Продолжать',
      'ta': 'தொடரவும்',
      'tl': 'Magpatuloy',
      'zh_Hans': '继续',
    },
    '4kzvc4zd': {
      'en': 'Home',
      'de': 'Heim',
      'id': 'Rumah',
      'ms': 'Rumah',
      'ru': 'Дом',
      'ta': 'வீடு',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // VerifySMSCode
  {
    '6wvtugmr': {
      'en': 'Verify SMS Code',
      'de': 'SMS-Code überprüfen',
      'id': 'Verifikasi Kode SMS',
      'ms': 'Sahkan Kod SMS',
      'ru': 'Подтвердить SMS-код',
      'ta': 'SMS குறியீட்டைச் சரிபார்க்கவும்',
      'tl': 'I-verify ang SMS Code',
      'zh_Hans': '验证短信代码',
    },
    'mcjfd8o6': {
      'en': 'Enter the code you recieved to continue.',
      'de': 'Geben Sie den Code ein, den Sie erhalten haben, um fortzufahren.',
      'id': 'Masukkan kode yang Anda terima untuk melanjutkan.',
      'ms': 'Masukkan kod yang anda terima untuk meneruskan.',
      'ru': 'Введите полученный код, чтобы продолжить.',
      'ta': 'தொடர, நீங்கள் பெற்ற குறியீட்டை உள்ளிடவும்.',
      'tl': 'Ilagay ang code na iyong natanggap upang magpatuloy.',
      'zh_Hans': '输入您收到的代码以继续。',
    },
    '2mwjpi8j': {
      'en': 'Verify SMS Code',
      'de': 'SMS-Code überprüfen',
      'id': 'Verifikasi Kode SMS',
      'ms': 'Sahkan Kod SMS',
      'ru': 'Подтвердить SMS-код',
      'ta': 'SMS குறியீட்டைச் சரிபார்க்கவும்',
      'tl': 'I-verify ang SMS Code',
      'zh_Hans': '验证短信代码',
    },
    'ia7pur3y': {
      'en': 'Home',
      'de': 'Heim',
      'id': 'Rumah',
      'ms': 'Rumah',
      'ru': 'Дом',
      'ta': 'வீடு',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // ProductDetails
  {
    'cah7zcf7': {
      'en': 'Description from Title',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    '14bntzxn': {
      'en': 'Description from Image',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'sn7g6tvp': {
      'en': 'Small',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'al4zkr1y': {
      'en': 'Medium',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    '7t04qri9': {
      'en': 'Large',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'dj4x0w91': {
      'en': 'Select a Size',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    '5t8az0g0': {
      'en': 'Add to Cart',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'qk8q05eb': {
      'en': 'Home',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // HomePage
  {
    'mxqx87v6': {
      'en': 'Welcome,',
      'de': 'Willkommen,',
      'id': 'Selamat datang,',
      'ms': 'selamat datang,',
      'ru': 'Добро пожаловать,',
      'ta': 'வரவேற்பு,',
      'tl': 'maligayang pagdating,',
      'zh_Hans': '欢迎，',
    },
    'ct34e9un': {
      'en': 'You Completed All Activities!',
      'de': 'Sie haben alle Aktivitäten abgeschlossen!',
      'id': 'Anda Menyelesaikan Semua Aktivitas!',
      'ms': 'Anda Selesai Semua Aktiviti!',
      'ru': 'Вы завершили все действия!',
      'ta': 'நீங்கள் அனைத்து செயல்பாடுகளையும் முடித்துவிட்டீர்கள்!',
      'tl': 'Nakumpleto Mo ang Lahat ng Aktibidad!',
      'zh_Hans': '您完成了所有活动！',
    },
    'kc7ior8c': {
      'en': 'Explore activity results below.',
      'de': 'Entdecken Sie unten die Aktivitätsergebnisse.',
      'id': 'Jelajahi hasil aktivitas di bawah ini.',
      'ms': 'Teroka hasil aktiviti di bawah.',
      'ru': 'Изучите результаты деятельности ниже.',
      'ta': 'செயல்பாட்டு முடிவுகளை கீழே ஆராயவும்.',
      'tl': 'Galugarin ang mga resulta ng aktibidad sa ibaba.',
      'zh_Hans': '浏览下面的活动结果。',
    },
    'kwpzkirm': {
      'en': 'Search on Cymbal',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'lf1g6mkx': {
      'en': 'Home',
      'de': 'Heim',
      'id': 'Rumah',
      'ms': 'Rumah',
      'ru': 'Дом',
      'ta': 'வீடு',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // Results
  {
    'kkgadjev': {
      'en': 'You Completed All Activities!',
      'de': 'Sie haben alle Aktivitäten abgeschlossen!',
      'id': 'Anda Menyelesaikan Semua Aktivitas!',
      'ms': 'Anda Selesai Semua Aktiviti!',
      'ru': 'Вы завершили все действия!',
      'ta': 'நீங்கள் அனைத்து செயல்பாடுகளையும் முடித்துவிட்டீர்கள்!',
      'tl': 'Nakumpleto Mo ang Lahat ng Aktibidad!',
      'zh_Hans': '您完成了所有活动！',
    },
    'wjdf5nvp': {
      'en': 'Explore activity results below.',
      'de': 'Entdecken Sie unten die Aktivitätsergebnisse.',
      'id': 'Jelajahi hasil aktivitas di bawah ini.',
      'ms': 'Teroka hasil aktiviti di bawah.',
      'ru': 'Изучите результаты деятельности ниже.',
      'ta': 'செயல்பாட்டு முடிவுகளை கீழே ஆராயவும்.',
      'tl': 'Galugarin ang mga resulta ng aktibidad sa ibaba.',
      'zh_Hans': '浏览下面的活动结果。',
    },
    'ogq0k6f8': {
      'en': 'Home',
      'de': 'Heim',
      'id': 'Rumah',
      'ms': 'Rumah',
      'ru': 'Дом',
      'ta': 'வீடு',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // Home
  {
    '6xutal08': {
      'en': 'Home',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'idr70pdf': {
      'en': 'About us',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'oth5i477': {
      'en': 'Shop',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    '8lvw0mr1': {
      'en': 'Blog',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'k23a90jl': {
      'en': 'Elegance is good taste, plus a dash of daring.',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    '5kme7qcj': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ualxdsws': {
      'en': 'Home',
      'de': 'Heim',
      'id': 'Rumah',
      'ms': 'Rumah',
      'ru': 'Дом',
      'ta': 'வீடு',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // addFullName
  {
    'n0xyhzdk': {
      'en': 'What is your name?',
      'de': 'Wie heissen Sie?',
      'id': 'Siapa namamu?',
      'ms': 'siapa nama awak',
      'ru': 'Как вас зовут?',
      'ta': 'உங்கள் பெயர் என்ன?',
      'tl': 'ano pangalan mo',
      'zh_Hans': '你叫什么名字？',
    },
    'rltaz5wn': {
      'en': 'Enter your full name below to continue.',
      'de': 'Geben Sie unten Ihren vollständigen Namen ein, um fortzufahren.',
      'id': 'Masukkan nama lengkap Anda di bawah untuk melanjutkan.',
      'ms': 'Masukkan nama penuh anda di bawah untuk meneruskan.',
      'ru': 'Введите свое полное имя ниже, чтобы продолжить.',
      'ta': 'தொடர உங்கள் முழுப் பெயரையும் கீழே உள்ளிடவும்.',
      'tl': 'Ilagay ang iyong buong pangalan sa ibaba upang magpatuloy.',
      'zh_Hans': '在下面输入您的全名以继续。',
    },
    'hh0gsms1': {
      'en': 'Full name',
      'de': 'Vollständiger Name',
      'id': 'Nama lengkap',
      'ms': 'Nama penuh',
      'ru': 'Полное имя',
      'ta': 'முழு பெயர்',
      'tl': 'Buong pangalan',
      'zh_Hans': '全名',
    },
    'dyx8b0ed': {
      'en': 'Full name is required.',
      'de': 'Der vollständige Name ist erforderlich.',
      'id': 'Nama lengkap diperlukan.',
      'ms': 'Nama penuh diperlukan.',
      'ru': 'Требуется полное имя.',
      'ta': 'முழு பெயர் தேவை.',
      'tl': 'Kinakailangan ang buong pangalan.',
      'zh_Hans': '需要全名。',
    },
    'o5rr3fcy': {
      'en': 'Please choose an option from the dropdown',
      'de': 'Bitte wählen Sie eine Option aus der Dropdown-Liste aus',
      'id': 'Silakan pilih opsi dari dropdown',
      'ms': 'Sila pilih pilihan daripada menu lungsur',
      'ru': 'Пожалуйста, выберите вариант из раскрывающегося списка',
      'ta': 'கீழ்தோன்றலில் இருந்து ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும்',
      'tl': 'Mangyaring pumili ng opsyon mula sa dropdown',
      'zh_Hans': '请从下拉列表中选择一个选项',
    },
    'sdxclykb': {
      'en': 'Check In',
      'de': 'Einchecken',
      'id': 'Mendaftar',
      'ms': 'Daftar masuk',
      'ru': 'Регистрироваться',
      'ta': 'செக் இன்',
      'tl': 'Mag-check In',
      'zh_Hans': '报到',
    },
  },
  // confirmLogout
  {
    '86ugdwuf': {
      'en': 'Do you want to log out?',
      'de': 'Möchten Sie sich abmelden?',
      'id': 'Apakah Anda ingin logout?',
      'ms': 'Adakah anda mahu log keluar?',
      'ru': 'Выйти?',
      'ta': 'வெளியேற விரும்புகிறீர்களா?',
      'tl': 'Gusto mo bang mag log out?',
      'zh_Hans': '你想退出吗？',
    },
    '9ee2z0tb': {
      'en':
          'You\'ll need to enter your credentials to access your account if you log out.',
      'de':
          'Wenn Sie sich abmelden, müssen Sie Ihre Anmeldedaten eingeben, um auf Ihr Konto zuzugreifen.',
      'id':
          'Anda harus memasukkan kredensial Anda untuk mengakses akun Anda jika Anda keluar.',
      'ms':
          'Anda perlu memasukkan kelayakan anda untuk mengakses akaun anda jika anda log keluar.',
      'ru':
          'Вам нужно будет ввести свои учетные данные, чтобы получить доступ к своей учетной записи, если вы выйдете из системы.',
      'ta':
          'நீங்கள் வெளியேறினால், உங்கள் கணக்கை அணுக உங்கள் நற்சான்றிதழ்களை உள்ளிட வேண்டும்.',
      'tl':
          'Kakailanganin mong ilagay ang iyong mga kredensyal upang ma-access ang iyong account kung mag-log out ka.',
      'zh_Hans': '如果您注销，则需要输入您的凭据才能访问您的帐户。',
    },
    'm9cacmxf': {
      'en': 'Log Out',
      'de': 'Ausloggen',
      'id': 'Keluar',
      'ms': 'Log keluar',
      'ru': 'Выйти',
      'ta': 'வெளியேறு',
      'tl': 'Log Out',
      'zh_Hans': '登出',
    },
    'hpdocfwp': {
      'en': 'Cancel',
      'de': 'Stornieren',
      'id': 'Membatalkan',
      'ms': 'Batal',
      'ru': 'Отмена',
      'ta': 'ரத்து செய்',
      'tl': 'Kanselahin',
      'zh_Hans': '取消',
    },
  },
  // placeHolder
  {
    'fx5w5irz': {
      'en': 'Search for product',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // selectLanguage
  {
    'ywpk4hyt': {
      'en': 'Select a Language to continue..',
      'de': 'Möchten Sie sich abmelden?',
      'id': 'Apakah Anda ingin logout?',
      'ms': 'Adakah anda mahu log keluar?',
      'ru': 'Выйти?',
      'ta': 'வெளியேற விரும்புகிறீர்களா?',
      'tl': 'Gusto mo bang mag log out?',
      'zh_Hans': '你想退出吗？',
    },
    '6cs19fmb': {
      'en': 'Option 1',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'stspvbx2': {
      'en': 'Please select...',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'scrfswrs': {
      'en': 'Search for an item...',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    '8sxaxm4v': {
      'en': 'Continue',
      'de': 'Stornieren',
      'id': 'Membatalkan',
      'ms': 'Batal',
      'ru': 'Отмена',
      'ta': 'ரத்து செய்',
      'tl': 'Kanselahin',
      'zh_Hans': '取消',
    },
  },
  // Miscellaneous
  {
    'sufyuu0e': {
      'en': 'Button',
      'de': 'Taste',
      'id': 'Tombol',
      'ms': 'Butang',
      'ru': 'Кнопка',
      'ta': 'பொத்தானை',
      'tl': 'Pindutan',
      'zh_Hans': '按钮',
    },
    'a0bznu5f': {
      'en': 'Button Medium',
      'de': 'Knopf mittel',
      'id': 'Tombol Sedang',
      'ms': 'Butang Sederhana',
      'ru': 'Кнопка Средняя',
      'ta': 'பொத்தான் மீடியம்',
      'tl': 'Katamtamang Pindutan',
      'zh_Hans': '按钮中号',
    },
    'l7rum3dw': {
      'en': 'Button Medium',
      'de': 'Knopf mittel',
      'id': 'Tombol Sedang',
      'ms': 'Butang Sederhana',
      'ru': 'Кнопка Средняя',
      'ta': 'பொத்தான் மீடியம்',
      'tl': 'Katamtamang Pindutan',
      'zh_Hans': '按钮中号',
    },
    '6at1jpmb': {
      'en': 'Label here...',
      'de': 'Hier beschriften...',
      'id': 'Beri label di sini...',
      'ms': 'Label di sini...',
      'ru': 'Этикетка здесь...',
      'ta': 'இங்கே லேபிளிடு...',
      'tl': 'Label dito...',
      'zh_Hans': '在这里标注...',
    },
    '64jtdfbi': {
      'en': 'Button',
      'de': 'Taste',
      'id': 'Tombol',
      'ms': 'Butang',
      'ru': 'Кнопка',
      'ta': 'பொத்தானை',
      'tl': 'Pindutan',
      'zh_Hans': '按钮',
    },
    '1omkt1sv': {
      'en': 'Button Medium',
      'de': 'Melden Sie sich ohne Telefon an',
      'id': 'Masuk tanpa ponsel',
      'ms': 'Log masuk tanpa telefon',
      'ru': 'Войти без телефона',
      'ta': 'தொலைபேசி இல்லாமல் உள்நுழைக',
      'tl': 'Mag-sign in nang walang telepono',
      'zh_Hans': '不用手机登录',
    },
    'x4ski9if': {
      'en': 'Button',
      'de': 'Taste',
      'id': 'Tombol',
      'ms': 'Butang',
      'ru': 'Кнопка',
      'ta': 'பொத்தானை',
      'tl': 'Pindutan',
      'zh_Hans': '按钮',
    },
    'dgfi02kw': {
      'en': 'Button Medium',
      'de': 'Knopf mittel',
      'id': 'Tombol Sedang',
      'ms': 'Butang Sederhana',
      'ru': 'Кнопка Средняя',
      'ta': 'பொத்தான் மீடியம்',
      'tl': 'Katamtamang Pindutan',
      'zh_Hans': '按钮中号',
    },
    'osxicpi0': {
      'en': 'Button',
      'de': 'Taste',
      'id': 'Tombol',
      'ms': 'Butang',
      'ru': 'Кнопка',
      'ta': 'பொத்தானை',
      'tl': 'Pindutan',
      'zh_Hans': '按钮',
    },
    'ujwkqlnf': {
      'en': 'Button Medium',
      'de': 'Knopf mittel',
      'id': 'Tombol Sedang',
      'ms': 'Butang Sederhana',
      'ru': 'Кнопка Средняя',
      'ta': 'பொத்தான் மீடியம்',
      'tl': 'Katamtamang Pindutan',
      'zh_Hans': '按钮中号',
    },
    '8m8kp6cg': {
      'en': 'Pending',
      'de': 'Ausstehend',
      'id': 'Tertunda',
      'ms': 'Yang belum selesai',
      'ru': 'В ожидании',
      'ta': 'நிலுவையில் உள்ளது',
      'tl': 'Nakabinbin',
      'zh_Hans': '待办的',
    },
    'n6tcdgjd': {
      'en': 'In Review',
      'de': 'Im Rückblick',
      'id': 'Di Tinjau',
      'ms': 'Dalam Semakan',
      'ru': 'В обзоре',
      'ta': 'மதிப்பாய்வில்',
      'tl': 'Sa Pagsusuri',
      'zh_Hans': '审查中',
    },
    '9fa2gae9': {
      'en': 'Complete',
      'de': 'Vollständig',
      'id': 'Menyelesaikan',
      'ms': 'lengkap',
      'ru': 'Полный',
      'ta': 'முழுமை',
      'tl': 'Kumpleto',
      'zh_Hans': '完全的',
    },
    'eowwrk8f': {
      'en': 'Please select...',
      'de': 'Bitte auswählen...',
      'id': 'Silahkan pilih...',
      'ms': 'Sila pilih...',
      'ru': 'Пожалуйста выберите...',
      'ta': 'தயவு செய்து தேர்வு செய்யவும்...',
      'tl': 'Pakipili...',
      'zh_Hans': '请选择...',
    },
    '691mussr': {
      'en': 'Search for an item...',
      'de': 'Nach einem Artikel suchen...',
      'id': 'Telusuri item...',
      'ms': 'Cari item...',
      'ru': 'Поиск элемента...',
      'ta': 'ஒரு பொருளைத் தேடு...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索项目...',
    },
    'wwtr9kc9': {
      'en': 'Button Medium',
      'de': 'Knopf mittel',
      'id': 'Tombol Sedang',
      'ms': 'Butang Sederhana',
      'ru': 'Кнопка Средняя',
      'ta': 'பொத்தான் மீடியம்',
      'tl': 'Katamtamang Pindutan',
      'zh_Hans': '按钮中号',
    },
    'h7zrpdyg': {
      'en': 'Button',
      'de': 'Taste',
      'id': 'Tombol',
      'ms': 'Butang',
      'ru': 'Кнопка',
      'ta': 'பொத்தானை',
      'tl': 'Pindutan',
      'zh_Hans': '按钮',
    },
    'c1rar5j5': {
      'en': 'Label here...',
      'de': 'Hier beschriften...',
      'id': 'Beri label di sini...',
      'ms': 'Label di sini...',
      'ru': 'Этикетка здесь...',
      'ta': 'இங்கே லேபிளிடு...',
      'tl': 'Label dito...',
      'zh_Hans': '在这里标注...',
    },
    'gfylvcfe': {
      'en': 'Button Medium',
      'de': 'Knopf mittel',
      'id': 'Tombol Sedang',
      'ms': 'Butang Sederhana',
      'ru': 'Кнопка Средняя',
      'ta': 'பொத்தான் மீடியம்',
      'tl': 'Katamtamang Pindutan',
      'zh_Hans': '按钮中号',
    },
    '7aoge1s3': {
      'en': 'Button',
      'de': 'Taste',
      'id': 'Tombol',
      'ms': 'Butang',
      'ru': 'Кнопка',
      'ta': 'பொத்தானை',
      'tl': 'Pindutan',
      'zh_Hans': '按钮',
    },
    'e4a2mpkb': {
      'en': 'All',
      'de': 'Alle',
      'id': 'Semua',
      'ms': 'Semua',
      'ru': 'Все',
      'ta': 'அனைத்து',
      'tl': 'Lahat',
      'zh_Hans': '全部',
    },
    '3ko19757': {
      'en': 'Custom Code',
      'de': 'Benutzerdefinierter Code',
      'id': 'Kode Kustom',
      'ms': 'Kod Tersuai',
      'ru': 'Пользовательский код',
      'ta': 'தனிப்பயன் குறியீடு',
      'tl': 'Custom na Code',
      'zh_Hans': '自定义代码',
    },
    'di14my7d': {
      'en': 'Page & Component',
      'de': 'Seite und Komponente',
      'id': 'Halaman & Komponen',
      'ms': 'Halaman & Komponen',
      'ru': 'Страница и компонент',
      'ta': 'பக்கம் & கூறு',
      'tl': 'Pahina at Bahagi',
      'zh_Hans': '页面和组件',
    },
    'ek3wl0bp': {
      'en': 'Sample Apps',
      'de': 'Beispiel-Apps',
      'id': 'Contoh Aplikasi',
      'ms': 'Contoh Apl',
      'ru': 'Примеры приложений',
      'ta': 'மாதிரி பயன்பாடுகள்',
      'tl': 'Mga Sample na App',
      'zh_Hans': '示例应用程序',
    },
    'qmk3v3od': {
      'en': 'All',
      'de': 'Alle',
      'id': 'Semua',
      'ms': 'Semua',
      'ru': 'Все',
      'ta': 'அனைத்து',
      'tl': 'Lahat',
      'zh_Hans': '全部',
    },
    'bjh1a9k0': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'kq6k9p4d': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    '84t84c1u': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'c10s37zo': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    '1ky0ty16': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    '4510kdli': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    '5i59ah85': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'vux90g9v': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'r3dd40vb': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    '38zl6nmi': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ftkpr256': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    '1ctsmcdv': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'xitqvlrk': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'dbuwmfz3': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'xqyzgpt4': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'd91tfl69': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'k6ulrzwk': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'v0a95ozc': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'al9vr18u': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'a6f9ksp3': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'isvei09f': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'l4k4bh3f': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    't4zw1dbt': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'wh2b2pix': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ld7ywy48': {
      'en': '',
      'de': '',
      'id': '',
      'ms': '',
      'ru': '',
      'ta': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
